/* Aqui se inicia la división de la tabla general en varias mas especificas*/
-- Verificar tabla general
SELECT * FROM trafico_maritimo;
SELECT ZONA_PORTUARIA, SOCIEDAD_PORTUARIA, TIPO_CARGA, EXPORTACION, IMPORTACIÓN, AÑO_VIGENCIA FROM trafico_maritimo;

-- Creación tabla puerto a partir de la original
CREATE TABLE CARGA SELECT ZONA_PORTUARIA, SOCIEDAD_PORTUARIA, TIPO_CARGA, EXPORTACION, IMPORTACIÓN, AÑO_VIGENCIA FROM trafico_maritimo;
SELECT * FROM CARGA;

-- Agregar columna id
ALTER TABLE CARGA ADD CARGA_ID INT NOT NULL auto_increment PRIMARY KEY;

-- Verficiar tabla nueva
SELECT * FROM CARGA;

-- Cambiar de lugar la columna id
ALTER TABLE CARGA MODIFY COLUMN CARGA_ID INT AFTER ZONA_PORTUARIA;
ALTER TABLE CARGA MODIFY COLUMN ZONA_PORTUARIA VARCHAR(50) AFTER CARGA_ID;

-- Agregar referencia a tabla provincia
ALTER TABLE CARGA ADD PROVINCIA_ID INT;
ALTER TABLE CARGA ADD PUERTO_ID INT;
ALTER TABLE CARGA ADD AÑO_ID INT;
ALTER TABLE CARGA ADD CONSTRAINT FK_PROVINCIA_ID_2 FOREIGN KEY (PROVINCIA_ID) REFERENCES PROVINCIA (PROVINCIA_ID);
ALTER TABLE CARGA ADD CONSTRAINT FK_PUERTO_ID FOREIGN KEY (PUERTO_ID) REFERENCES PUERTO (PUERTO_ID);
ALTER TABLE CARGA ADD CONSTRAINT FK_AÑO_ID FOREIGN KEY (AÑO_ID) REFERENCES AÑO (AÑO_ID);