/* Aqui se inicia la división de la tabla general en varias mas especificas*/
-- Verificar tabla general
SELECT * FROM trafico_maritimo;
SELECT ZONA_PORTUARIA, TIPO_CARGA, TRANSBORDO, FLUVIAL, CABOTAJE, MOVILIZACIONES_BORDO, TRANSITORIA, AÑO_VIGENCIA FROM trafico_maritimo;

-- Creación tabla puerto a partir de la original
CREATE TABLE TRANSACCIONES SELECT ZONA_PORTUARIA, TIPO_CARGA, TRANSBORDO, FLUVIAL, CABOTAJE, MOVILIZACIONES_BORDO, TRANSITORIA, AÑO_VIGENCIA FROM trafico_maritimo;
SELECT * FROM TRANSACCIONES;

-- Agregar columna id
ALTER TABLE TRANSACCIONES ADD TRANSACCION_ID INT NOT NULL auto_increment PRIMARY KEY;

-- Verficiar tabla nueva
SELECT * FROM TRANSACCIONES;

-- Cambiar de lugar la columna id
ALTER TABLE TRANSACCIONES MODIFY COLUMN TRANSACCION_ID INT AFTER ZONA_PORTUARIA;
ALTER TABLE TRANSACCIONES MODIFY COLUMN ZONA_PORTUARIA VARCHAR(50) AFTER TRANSACCION_ID;

-- Agregar referencia a tabla provincia
ALTER TABLE TRANSACCIONES ADD PUERTO_ID INT;
ALTER TABLE TRANSACCIONES ADD CARGA_ID INT;
ALTER TABLE TRANSACCIONES ADD AÑO_ID INT;
ALTER TABLE TRANSACCIONES ADD CONSTRAINT FK_PUERTO_ID_2 FOREIGN KEY (PUERTO_ID) REFERENCES PUERTO (PUERTO_ID);
ALTER TABLE TRANSACCIONES ADD CONSTRAINT FK_CARGA_ID FOREIGN KEY (CARGA_ID) REFERENCES CARGA (CARGA_ID);
ALTER TABLE TRANSACCIONES ADD CONSTRAINT FK_AÑO_ID_2 FOREIGN KEY (AÑO_ID) REFERENCES AÑO (AÑO_ID);